POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

{
  "username":"Nikki",
  "password":"13579",
  "email":"gaya@gmail.com",
  "name":"Gaya"
}

###

POST  http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
 
  "email":"gaya@gmail.com",
   "password":"13579"
 
}

###

GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
 "token": "8e7960548060842008a7928766b98a8ec6888d661d6445f45aadb06be57a52d7"
}

###

POST http://localhost:9090/update_profile_data
Content-Type: application/json

{
  "token": "41c75285174cf8ce3c949901ea7976f437b8321519d57303f6be5e4efe592277",
  "bio":"Hii i'm Itishree . I am from india",
  "currentPost":"CTO",
  "pastWork":[
    {
      "company":"Microsoft",
      "position":"CTO",
      "years":"2+"
    }
  ],
  "education":[
    {
      "school":"BCET",
      "degree":"B.Tech",
      "fieldOfStudy":"2022-2026"
    }
  ]
}

###

GET http://localhost:9090/user/get_all_users

